server:
  port: 8085
  servlet:
    context-path: /
    multipart:
      maxFileSize: 20Mb
      maxRequestSize: 20Mb
    maxHttpHeaderSize: 102400000
    maxHttpPostSize: 102400000
# mysql
spring:
  datasource:
    #driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/psycholog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    #url: jdbc:mysql://47.106.190.35:3306/psycholog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    #username: root
    #password: yan921223830
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: false
      wall:
        config:
          multi-statement-allow: true
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
      enabled: true
  #http:
  #  multipart:
  #    max-file-size: 20Mb
  #    max-request-size: 60Mb
  devtools:
    restart:
      enabled: true
      additional-paths: psycholog/src/main/java
      exclude: templates/**
    freemarker:
      cache: false
renren:
  redis:
    open: false
  shiro:
    redis: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.psycholog.module.dao
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




